club_traffic/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from posts.views import my_signup, ProfileEdit
from . import views as club_traffic_home_view
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', club_traffic_home_view.home),
    url(r'^accounts/signup/', my_signup),
    url(r'^accounts/profile/', ProfileEdit.as_view(), name='profile'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^posts/', include("posts.urls")),
    url(r'^business/', include("business.urls")),
    url(r'^location/', include("member_location.urls")),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

posts/urls.py
from django.conf.urls import url

from posts.views import Follow, FollowType, PostsLocationsList
from . import views


urlpatterns = [
    url(r'^$', "posts.views.post_list"),
    url(r'^create/$', "posts.views.post_create"),
    url(r'^(?P<id>\d+)/$', "posts.views.post_detail"),
    url(r'^update/$', "posts.views.post_update"),
    url(r'^delete/$', "posts.views.post_delete"),
    url(r'^follow/(?P<post_id>\d+)/$', Follow.as_view()),
    url(r'^follow/type/$', FollowType.as_view()),
    url(r'^locations/$', PostsLocationsList.as_view()),
    url(r'^getClub/$', views.getClub),
    url(r'^updateClub/$', views.updateClub),
    url(r'^deleteClub/$', views.deleteClub),
    url(r'^rateBusiness/$', views.rateBusiness),
    url(r'^search/$', views.search),
    
]

posts/models.py
from django.db.models import Count
from django.utils import timezone
from django.contrib.auth.models import AbstractUser, BaseUserManager
from polymorphic.models import PolymorphicModel

from posts.validators import mail_domain_validator
from django.db import models


class Post(PolymorphicModel):
    SELECT_AGE = (
        ('l', '18-22'),
        ('m', '23-27'),
        ('h', '28-32')
    )
    title = models.CharField(max_length=120)
    content = models.TextField()
    image = models.FileField(null=True, blank=True)
    location = models.ForeignKey('Location')
    x_coordinate = models.FloatField(null=True)
    y_coordinate = models.FloatField(null=True)
    address = models.CharField(max_length=255, null=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    rate = models.FloatField(null=True, default = 0 )
    phone_number = models.CharField(max_length = 30, null="True")
    hours_of_operation = models.IntegerField(null="True")
    cover_price = models.FloatField(null="True")
    dress_code = models.CharField(max_length = 255, null="True")
    capacity = models.IntegerField(null="True")
    # age_restriction = models.SmallIntegerField(null="True")
    age_restriction = models.CharField(choices=SELECT_AGE, max_length = 1, null=True)
    # age_restriction = models.
    website = models.URLField(null="True")
    type_of_music = models.CharField(max_length=255, null="True")
    user = models.ForeignKey('MyUser' , null=True, related_name="all_post")
    date_party = models.DateField(null = True)
    def get_absolute_url(self):
        return "/posts/{}/".format(self.id)

    def type_count(self):
        type_array = []
        followed_users_type_count = MyUser.objects.values(
            'following_type'
        ).filter(
            following=self
        ).annotate(
            count=Count('following_type')
        )
        single = 0
        taken = 0
        confused = 0

        for type_count in followed_users_type_count:
            if type_count['following_type'] == 'single':
                single = type_count['count']
            elif type_count['following_type'] == 'taken':
                taken = type_count['count']
            elif type_count['following_type'] == 'confused':
                confused = type_count['count']

        return_dict = {
            'single': single,
            'taken': taken,
            'confused': confused
        }
        return return_dict
    def is_business(self):
        return False
    def __unicode__(self):
        return u"%s"%self.title

class Event(Post):
    # club = models.ForeignKey('MyUser', related_name="all_event")
    pass



class MyUserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, username, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        now = timezone.now()
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(username=username, email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        return self._create_user(username, email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        return self._create_user(username, email, password, True, True,
                                 **extra_fields)


class MyUser(AbstractUser):
    objects = MyUserManager()

    FOLLOWING_TYPE_CHOICES = (
        ('single', 'single'),
        ('taken', 'taken'),
        ('confused', 'confused'),
    )
    SELECT_SEX = (
        ('ma', 'male'),
        ('fe', 'female')
    )
    class Meta:
        db_table = 'auth_user'

    def __init__(self, *args, **kwargs):
        AbstractUser.__init__(self, *args, **kwargs)

    profile_photo = models.ImageField(null=True, blank=True, upload_to="avatar")
    following = models.ForeignKey('Post', null=True, blank=True)
    location = models.ForeignKey('Location', null=True)
    following_type = models.CharField(choices=FOLLOWING_TYPE_CHOICES, max_length=10, null=True, blank = True)
    is_business = models.BooleanField(default=False)
    business_name = models.CharField(max_length=255, null=True, blank = True)
    sex = models.CharField(choices=SELECT_SEX, max_length = 2, default = 'ma')
    lat_current = models.FloatField(null = True)
    lng_current = models.FloatField(null = True)
    def getListLocation(self):
        return Location.objects.all()
        
class Location(models.Model):
    name = models.CharField(max_length=200)
    def __unicode__(self):
        return u'%s'%self.name

posts/views.py
import datetime
from allauth import app_settings
from googlemaps import googlemaps
from allauth.account.utils import passthrough_next_redirect_url, complete_signup
from allauth.account.views import SignupView
from allauth.utils import get_request_param
from braces.views import JsonRequestResponseMixin, CsrfExemptMixin, LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, FormView
from googlemaps.exceptions import _RetriableRequest, ApiError

from club_traffic import settings
from .models import Event, Location, MyUser, Post
from .forms import PostForm, ProfileForm, SingleOrTaken
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from business.models import Business, RateBusines
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from business.forms import BusinessForm
try:
    import json
except ImportError:
    import simplejson as json


class Follow(CsrfExemptMixin, JsonRequestResponseMixin, LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if kwargs['post_id']:
            try:
                post = Event.objects.get(pk=kwargs['post_id'])
            except ObjectDoesNotExist:
                return self.render_bad_request_response({'message': 'Post does not exist'})
            user = MyUser.objects.get(pk=request.user.id)
            if user.following == post:
                return self.render_bad_request_response({'message': 'Already following that post'})
            else:
                user.following = post
                user.save()
                updated_post = Event.objects.filter(pk=kwargs['post_id']).annotate(
                    followers_count=Count('myuser')).get()
                return self.render_json_response({'followers_count': updated_post.followers_count})
        else:
            return self.render_bad_request_response({'message': 'Post id not provided'})


class PostsLocationsList(CsrfExemptMixin, JsonRequestResponseMixin, LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        post_array = []
        today = datetime.date.today()
        posts = Event.objects.filter(x_coordinate__isnull=False, y_coordinate__isnull=False)
        if posts.exists():
            for post in posts:
                post_array.append({
                    'longitude': post.x_coordinate,
                    'latitude': post.y_coordinate,
                    'id': post.id
                })
            return self.render_json_response(post_array)
        else:
            return self.render_bad_request_response({'message': 'Out of Event'})


class FollowType(CsrfExemptMixin, JsonRequestResponseMixin, LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):

        try:
            user = MyUser.objects.get(pk=request.user.id)
            user.following_type = request.POST['following_type']
            user.save()
            return self.render_json_response({'following_type':user.following.type_count()})
        except (KeyError, ObjectDoesNotExist):
            return self.render_bad_request_response({'message': 'Invalid value'})


@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    success = False
    duplicated = False
    methodPost = False
    if form.is_valid():
        methodPost = True
        try:
            event = Event.objects.get(title = form.cleaned_data['title'], location = form.cleaned_data['location'] )
            duplicated = True
        except Event.DoesNotExist :
            pass

        if duplicated == False :   
            instance = form.save(commit=False)
            try:
                g_maps = googlemaps.Client(settings.GOOGLE_API_KEY)
                city_name = instance.location.name
                location_api_json = g_maps.geocode('{},{}'.format(form.cleaned_data['address'], city_name))
                instance.x_coordinate = location_api_json[0]['geometry']['location']['lat']
                instance.y_coordinate = location_api_json[0]['geometry']['location']['lng']
            except (ValueError,_RetriableRequest,ApiError):
                pass
            instance.save()
            success = True
    else:
        print(form.errors)

    context = {
        "form": form,
        "success": success,
        "duplicated": duplicated,
        "methodPost": methodPost
    }

    return render(request, "post_form.html", context)


@login_required
def post_detail(request, id):
    instance = get_object_or_404(Event, id=id)
    context = {
        "title": "Detail",
        "instance": instance,
    }
    return render(request, "post_detail.html", context)


@login_required
def post_list(request):
    single_or_taken_form = SingleOrTaken(request.POST or None)
    user_location = request.user.location
    queryset_list = Event.objects.filter(instance_of=Post, location=user_location, ).annotate(
        followers_count=Count('myuser')
    ).order_by(
        '-followers_count'
    )
    # Show 5 contacts per page
    paginator = Paginator(queryset_list, 10)

    page_request_variable = 'page'

    page = request.GET.get(page_request_variable)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
        "object_list": queryset,
        "title": "List",
        "page_request_var": page_request_variable,
        "single_or_taken_form": single_or_taken_form
    }
    return render(request, "posts.html", context)


@login_required
def post_update(request):
    context = {
        "title": "Update"
    }
    return render(request, "posts.html", context)


@login_required
def post_delete(request):
    context = {
        "title": "Delete"
    }
    return render(request, "posts.html", context)




class ProfileEdit(FormView, LoginRequiredMixin):
    template_name = 'account/profile_edit.html'
    form_class = ProfileForm
    def get_initial(self):
        
        if self.request.user.is_business :
            return {
                'location': self.request.user.location,
                'first_name': self.request.user.first_name,
                'last_name': self.request.user.last_name,
                'following': self.request.user.following,
                'following_type': self.request.user.following_type,
                'business_name': self.request.user.business_name,
                'profile_photo': self.request.user.profile_photo,
                'sex': self.request.user.sex,
            }
        else :
            return {
                'location': self.request.user.location,
                'first_name': self.request.user.first_name,
                'last_name': self.request.user.last_name,
                'following': self.request.user.following,
                'following_type': self.request.user.following_type,
                'profile_photo': self.request.user.profile_photo,
                'sex' : self.request.user.sex,
                # 'business_name': self.request.user.business_name,
            }
   
    def form_valid(self, form):

        location = form.cleaned_data['location']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        following = form.cleaned_data['following']
        following_type = form.cleaned_data['following_type']
        profile_photo = form.cleaned_data['profile_photo']
        business_name = form.cleaned_data['business_name']
        sex = form.cleaned_data['sex']
        user = MyUser.objects.get(id=self.request.user.id)
        user.first_name = first_name
        user.last_name = last_name
        user.following = following
        user.following_type = following_type
        user.sex = sex
        user.profile_photo = profile_photo
        user.location = location
        user.business_name = business_name
        user.save()
        return HttpResponseRedirect(reverse('profile'))

class MySignupView(SignupView):

    def get_context_data(self, **kwargs):
        ret = super(MySignupView, self).get_context_data(**kwargs)
        form = ret['form']
        form.fields["email"].initial = self.request.session.get('account_verified_email', None)
        login_url = passthrough_next_redirect_url(self.request,
                                                  reverse("account_login"),
                                                  self.redirect_field_name)
        redirect_field_name = self.redirect_field_name
        redirect_field_value = get_request_param(self.request,
                                                 redirect_field_name)
        locations = Location.objects.all()
        ret.update({"login_url": login_url,
                    "redirect_field_name": redirect_field_name,
                    "redirect_field_value": redirect_field_value,
                    'locations': locations})
        return ret
my_signup = MySignupView.as_view()


@csrf_exempt
def getClub(request):
    idClub = request.POST.get('idClub')
    club = Business.objects.get(id=idClub)
    # array_result = serializers.serialize('json', [club], ensure_ascii=False)
    # print array_result
    # just_object_result = {}

templates/base.html

<!DOCTYPE html>

{% load staticfiles %}
{% load account %}
<!-- This site was created in Webflow. http://www.webflow.com--><!-- Last Published: Wed Feb 17 2016 23:15:47 GMT+0000 (UTC) -->
<html data-wf-site="56c1eb0908edd1584134fb07" data-wf-page="56c1eb0a08edd1584134fb0c">
  <head>
    <meta charset="utf-8">
    {% block title %}{% endblock title %}
    <meta name="description" content="A modern, playful responsive website template to showcase your party for example. Perfect for musicians or party organizers.">
    <meta property="og:image" content="http://files.rowanhartsuiker.com/Studiocorvus/template-waiters.jpg">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="Webflow">

    <!-- My Custom CSS FILES !!! :D :D :D  -->
    {% block static %}{% endblock static%}

    <link rel="stylesheet" type="text/css" href="https://daks2k3a4ib2z.cloudfront.net/56c1eb0908edd1584134fb07/css/clubtrafic.webflow.eceb30560.css">

    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
    <script>
      WebFont.load({
        google: {
          families: ["Oswald:300,400,700","Montserrat:400,700","PT Sans:400,400italic,700,700italic","Lato:100,100italic,300,300italic,400,400italic,700,700italic,900,900italic","Roboto:100,300,regular,italic,500,500italic,700,900"]
        }
      });


    </script>
    <script type="text/javascript" src="https://daks2k3a4ib2z.cloudfront.net/0globals/modernizr-2.7.1.js"></script>
    <link rel="shortcut icon" type="image/x-icon" href="https://daks2k3a4ib2z.cloudfront.net/56c1eb0908edd1584134fb07/56c1eb0a08edd1584134fb4f_Favicon.png">
    <link rel="apple-touch-icon" href="https://daks2k3a4ib2z.cloudfront.net/56c1eb0908edd1584134fb07/56c1eb0a08edd1584134fb50_Webclip.jpg">
    <link rel="stylesheet" type="text/css" href="{% static 'static_root/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'static_root/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'static_root/css/styles.css' %}">
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  </head>
<body>




  <div data-ix="hide-popup" class="w-section popup">
    <div data-ix="hide-popup-block" class="popup-block">
      <div class="popup-content-block">
        <div class="popup-title">Contact us</div>
        <div class="popup-title subtitle">Got plans for a party?</div>
        <a href="#" data-ix="close-popup" class="w-inline-block close-popup-button">
          <img src="https://daks2k3a4ib2z.cloudfront.net/56c1eb0908edd1584134fb07/56c1eb0a08edd1584134fb41_Icon-close-white.png" class="close-icon">
        </a>

      </div>
      <div class="w-form popup-form">
        <form id="wf-form-Email-Form" name="wf-form-Email-Form" data-name="Email Form">
          <input id="name" type="text" placeholder="Enter your name" name="name" data-name="Name" class="w-input field">
          <input id="Phone" type="text" placeholder="Enter your phone number" name="Phone" data-name="Phone" class="w-input field">
          <input id="email-2" type="email" placeholder="Enter your email address" name="email" data-name="Email 2" required="required" class="w-input field">
          <textarea id="Message" placeholder="Enter message..." name="Message" data-name="Message" class="w-input field area"></textarea>
          <input type="submit" value="Submit" data-wait="Please wait..." class="w-button button submit">
        </form>
        <div class="w-form-done success-bg">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail error-bg">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
    </div>
  </div>
  <div data-ix="fixed-navbar" class="fixed-navbar-wrapper">
    <div data-collapse="medium" data-animation="over-left" data-duration="400" data-doc-height="1" class="w-nav navbar">
      <div class="w-container navbar-container">
        <a href="/" class="w-inline-block logo-container logo-hd">
          <img src="{% static 'static_root/img/Clubtrafic LOGO_multicolour_white_small.png' %}" class="img-responsive">
        </a>
        <nav role="navigation" class="w-nav-menu w-clearfix nav-menu">
          <a href="/" class="w-hidden-main w-inline-block logo-container responsive-menu">
            <div class="text-logo">Waiters</div>
            <div class="text-logo subtitle">Party organisers</div>
          </a>
          {% if request.user.is_authenticated %}
          <a href="/" class="w-nav-link nav-link">Home</a>
          {% endif %}
          
            {% if request.user.is_authenticated %}
                <a href="/posts/" class="w-nav-link nav-link">Events</a>
                <a href="/business/" class="w-nav-link nav-link">Clubs</a>
                <a href="/accounts/profile/" class="w-nav-link nav-link">Profile</a>
                <a href="/accounts/logout/" class="w-nav-link nav-link">logout </a>
            {% else %}
          <a href="/accounts/signup/" class="w-nav-link nav-link">get started now</a>
          <a href="/accounts/login/" class="w-nav-link nav-link">log in</a>
            {% endif %}
        </nav>
        <div class="w-nav-button menu-button">
          <div class="w-icon-nav-menu hamburger-icon"></div>
        </div>
      </div>
    </div>
  </div>
  
  <div data-ix="show-navbar" class="navbar-wrapper">
    <div data-collapse="medium" data-animation="over-left" data-duration="400" data-doc-height="1" class="w-nav navbar">
      <div class="w-container navbar-container">
        <a href="/" class="w-inline-block logo-container logo-hd">
          <img src="{% static 'static_root/img/Clubtrafic LOGO_multicolour_white_small.png' %}" class="img-responsive">
        </a>
        <nav role="navigation" class="w-nav-menu w-clearfix nav-menu">
          <a href="/" class="w-hidden-main w-inline-block logo-container responsive-menu">
            <div class="text-logo">Waiters</div>
            <div class="text-logo subtitle">Party organisers</div>
          </a>
          {% if request.user.is_authenticated %}
          <a href="/" class="w-nav-link nav-link">Home</a>
          {% endif %}
            {% if request.user.is_authenticated %}
                <a href="/posts/" class="w-nav-link nav-link">Events</a>
                <a href="/business/" class="w-nav-link nav-link">Clubs</a>
                <a href="/accounts/profile/" class="w-nav-link nav-link">Profile</a>
                <a href="/accounts/logout/" class="w-nav-link nav-link">logout </a>

            {% else %}
          <a href="/accounts/signup/" class="w-nav-link nav-link">get started now</a>
          <a href="/accounts/login/" class="w-nav-link nav-link">log in</a>
            {% endif %}
        </nav>
        <div class="w-nav-button menu-button">
          <div class="w-icon-nav-menu hamburger-icon"></div>
        </div>
      </div>
    </div>
  </div>




  {% block map %}
  <div id="top" data-ix="show-fixed-navbar" class="w-section page-header at-location"

  style = "
  margin-top: 0px;
  margin-bottom: -10px;
  "
  >
    <div class="page-header-overlay"></div>
  </div>
  <div class="w-section image-background-section pricing-plans">
    <div id="more-about-us" class="background-image-section-overlay pricing">

      {% block content %}{% endblock content %}


          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="w-section section red  " style="

    padding-bottom: 1000px;

    "></div>
  {% endblock %}

<script type="text/javascript" src="https://daks2k3a4ib2z.cloudfront.net/56c1eb0908edd1584134fb07/js/webflow.066cd5266.js"></script>
<!--[if lte IE 9]><script src="//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->

{% block boostrap %}
{% endblock %}


  <script>
  $(document).ready(function(){
    {% block jquery %}{% endblock %}
  });

</script>
</body>
</html>



templates/post_detail.html
{% extends "base.html" %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}
<div class='col-sm-6 col-sm-offset-3 post-ctn'>

<div class='row'>
<div class='col-sm-12'>

    <h1 style="color: #eaeaea; background-color: #0c0000">{{ instance.title }}</h1>
    <h6>Location: {{ instance.location.name }}</h6>
    <h4 style="color: #0c0000">Description: </h4>
    <h6 style="color: #d90246">{{ instance.content }}</h6>





<hr/>
<br/>

</div>
</div>


{% endblock content %}

templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static from staticfiles %} 
{% block title %}
<title>Create Event</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'static_root/css/dateUi.css' %}">


{% endblock %}

{% block content %}
<div class='container'>

    <div class='create-new-event col-sm-6 col-sm-offset-3'>
    <h1>Create a New Event</h1>
    {% if success == True %}
    <div class="alert alert-success">
      <strong>Successful</strong> You have created an event successfully
    </div>
    {% endif %}

    {% if methodPost == True and duplicated == True%}
      <div class="alert alert-danger">
        <strong>Duplicated!</strong> The title of this event already exists in this location
      </div>
    {% endif %}
    <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
    	{{ form|crispy }}
    	<input type='submit' class='btn btn-default' value='Create Post' />
    </form>
    </div>
</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
 <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
  <script>
	  $( function() {
	    $( "#id_date_party" ).datepicker();
	  } );
  </script>
{#    <script>#}
{#        function add_coordinates_success(data){#}
{#            var latitude = data.coords.latitude;#}
{#            var longitude = data.coords.longitude;#}
{#            $('#id_x_coordinate').val(latitude);#}
{#            $('#id_y_coordinate').val(longitude);#}
{##}
{#        }#}
{##}
{#        function add_coordinates_error(){#}
{#            // TODO show toast error#}
{#        }#}
{##}
{#        $( document ).ready(function() {#}
{#            navigator.geolocation.getCurrentPosition(add_coordinates_success,add_coordinates_error);#}
{#        });#}
{##}
{#    </script>#}

{% endblock content %}