club_traffic/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from posts.views import my_signup, ProfileEdit
from . import views as club_traffic_home_view
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', club_traffic_home_view.home),
    url(r'^accounts/signup/', my_signup),
    url(r'^accounts/profile/', ProfileEdit.as_view(), name='profile'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^posts/', include("posts.urls")),
    url(r'^business/', include("business.urls")),
    url(r'^location/', include("member_location.urls")),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

posts/urls.py
from django.conf.urls import url

from posts.views import Follow, FollowType, PostsLocationsList
from . import views


urlpatterns = [
    url(r'^$', "posts.views.post_list"),
    url(r'^create/$', "posts.views.post_create"),
    url(r'^(?P<id>\d+)/$', "posts.views.post_detail"),
    url(r'^update/$', "posts.views.post_update"),
    url(r'^delete/$', "posts.views.post_delete"),
    url(r'^follow/(?P<post_id>\d+)/$', Follow.as_view()),
    url(r'^follow/type/$', FollowType.as_view()),
    url(r'^locations/$', PostsLocationsList.as_view()),
    url(r'^getClub/$', views.getClub),
    url(r'^updateClub/$', views.updateClub),
    url(r'^deleteClub/$', views.deleteClub),
    url(r'^rateBusiness/$', views.rateBusiness),
    url(r'^search/$', views.search),
    
]

posts/forms.py
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django import forms
from django.contrib.auth import get_user_model
from .models import Event, Location, MyUser
from django.contrib.auth.forms import ReadOnlyPasswordHashField

class LocationModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name

STATUS_CHOICES = (
    ('single', 'Going as Single'),
    ('taken', 'Going with a Partner'),
    ('confused', 'Still not sure')

)


class SingleOrTaken(forms.Form):
    following_type = forms.CharField(label="Status", widget=forms.RadioSelect(choices=STATUS_CHOICES))


class PostForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            "title",
            "content",
            "image",
            "address",
            "location",
            "date_party"
        ]

    location = LocationModelChoiceField(queryset=Location.objects.all())


class MySignupForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password' , 'is_business','first_name', 'last_name', 'email', 'location', 'business_name']

    def signup(self, user):
        user.save()

    def clean_email(self):
        validate_email(self.cleaned_data['email'])
        if MyUser.objects.filter(email=self.cleaned_data['email']).exists():
            raise ValidationError('Email is not unique')
        if not self.cleaned_data['is_business']:
            if not (('@mail.usask.ca' or '@usask.ca') in self.cleaned_data['email']):
                raise ValidationError('Email domain is not allowed')
        return self.cleaned_data['email']

    def clean_business_name(self):
        if not self.cleaned_data['is_business'] : 
            if self.cleaned_data['business_name'] != "" :
                raise ValidationError('User doesent have business_name')
        elif not self.cleaned_data['business_name']:
            raise ValidationError('Business name needs to be filled out')
        return self.cleaned_data['business_name']

    def clean_password2(self):
        # Check that the two password entries match
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(MySignupForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    username = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30, render_value=False)), label=("Username"))
    first_name = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30, render_value=False)), label=("First Name"))
    last_name = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30, render_value=False)), label=("Last Name"))
    business_name = forms.CharField(label="Business name", required=False)
    password = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label="Password (again)")

   
# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = MyUser
#         fields = [
#             "first_name", 
#             "last_name",
#             "following",
#             "following_type",
#             "location",
#         ]
#     # location = LocationModelChoiceField(queryset=Location.objects.all())

class ProfileForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ('first_name', 'last_name', 'following', 'following_type', 'location', 'business_name', 'profile_photo', 'sex')
        first_name = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30, render_value=False)), label=("First Name"))
        last_name = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30, render_value=False)), label=("Last Name"))
        # business_name = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=30, render_value=False)), label=("Business Name"))
    def clean_first_name(self):
        # Check that the two password entries match
        first_name = self.cleaned_data.get("first_name")
        if first_name == "":
            raise ValidationError('First name needs to be filled out')
        return first_name

    def clean_last_name(self):
        # Check that the two password entries match
        last_name = self.cleaned_data.get("last_name")
        if last_name == "":
            raise ValidationError('Last name needs to be filled out')
        return last_name 

    # def clean_following_type(self):
    #     print "toi la type2322"
    #     following_type = self.cleaned_data.get("following_type")
    #     list_type = ["taken", "confused", "single"]
    #     if following_type not in list_type:
    #         raise ValidationError("this field is required")
    #     return following_type
    # def clean_business_name(self):
    #     # Check that the two password entries match
    #     business_name = self.cleaned_data.get("business_name")
    #     if business_name == "":
    #         raise ValidationError('Business name needs to be filled out')
    #     return business_name

templates/signups/signup.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'signups/css/signups.css' %}"
{% endblock %}

{% block title %}
<title>Sign Up</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
{% endblock %}



{% block content %}
<div class="container">

    <h1 class="heading_get_started">Get Started Now</h1>

    <p>Already have an account? Then please <a href="/accounts/login/">sign in</a>.</p>
    <form class="signup" id="signup_form" method="POST" action="/accounts/signup/">
        {% csrf_token %}
        <input autofocus="autofocus" id="id_username" maxlength="30" name="username" placeholder="Username" type="text" class="w-input">
        <input id="id_email" name="email" placeholder="E-mail address" type="email" class="w-input">
        <input id="id_business_name" name="business_name" placeholder="Business name" type="text" class="w-input">
        <input id="id_password1" name="password1" placeholder="Password" type="password" class="w-input">
        <input id="id_password2" name="password2" placeholder="Password (again)" type="password">
        <input type="submit" value="Sign up" data-wait="Please wait..." class="btn btn-primary btn-lg btn-block">
        </form>
    <div>
    {% if messages %}
        <div class="row">
            <div class="col-small-6 w-col-small-offset-12">
         <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags == "success" %} class="alert alert-success"{% endif %}><h5> {{ message }}</h5></li>
        {% endfor %}
             </ul>
                </div>
            </div>
    {% endif %}
        </div>

</div>






<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


{% endblock %}

templates/signups/thankyou.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'signups/css/signups.css' %}"
{% endblock %}

{% block title %}
<title>Thank You</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
{% endblock %}



{% block content %}
<div class="container">

    <h1 class="heading_get_started">Thank You for joining</h1>

</div>






<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


{% endblock %}